server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: 123456
  redis:
    database: 0
    host: 172.16.13.130
    port: 6379
    password: redis

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl